import type { MasteryCategory } from '@/types/mastery'

export const MASTERY_CATEGORIES: MasteryCategory[] = [
  {
    id: 'setup',
    label: 'セットアップ・基盤',
    icon: '⚙️',
    items: [
      {
        id: 'claude-md',
        label: 'CLAUDE.md の作成',
        completed: true,
        description: 'プロジェクトのルールと規約をClaude Codeに伝えるための設定ファイル。',
        detail: 'CLAUDE.md はリポジトリのルートに置くことで、Claude Code がプロジェクトに参加するたびに自動的に読み込まれます。コーディング規約・ディレクトリ構成・コミットルール・禁止事項などを記述しておくと、会話のたびに説明する手間がなくなります。サブディレクトリに置いた CLAUDE.md も再帰的に読み込まれるため、パッケージごとに固有のルールを記載することも可能です。',
        commands: ['cat CLAUDE.md', 'ls **/.claude/CLAUDE.md'],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/memory',
        usageExample: '新しいメンバーがプロジェクトに参加したとき、Claude Code が CLAUDE.md を自動読み込みするため「このプロジェクトは TypeScript で `any` 禁止」などのルールを毎回説明する必要がなくなった。チームの全員が同じ Claude の振る舞いを得られる。',
      },
      {
        id: 'github-push',
        label: 'GitHub リポジトリの作成・プッシュ',
        completed: true,
        description: 'gh コマンドでリモートリポジトリを作成し、初回コミットをプッシュする。',
        detail: 'Claude Code は gh CLI を活用してリポジトリの作成・PR作成・Issue管理まで一貫して行えます。`gh repo create` でリポジトリを作成し、`git push -u origin main` で初回プッシュまで完結できます。',
        commands: ['gh repo create <name> --public', 'git push -u origin main'],
        sourceUrl: 'https://cli.github.com/manual/',
        usageExample: 'スクラッチでプロジェクトを始めるとき、「GitHub リポジトリを作って初回コミットしてください」と依頼するだけで `gh repo create` → `git add` → `git commit` → `git push` まで一気通貫で完了する。',
      },
      {
        id: 'vercel-deploy',
        label: 'Vercel デプロイ',
        completed: true,
        description: 'vercel CLI を使って login / link / deploy の一連のフローを実行する。',
        detail: 'Vercel へのデプロイは `vercel login` → `vercel link` → `vercel deploy` の3ステップ。プロジェクトを Vercel に紐付けると GitHub と連携し、プッシュのたびに自動デプロイが走るようになります。`--prod` フラグで本番環境に直接デプロイできます。',
        commands: ['vercel login', 'vercel link', 'vercel deploy', 'vercel --prod'],
        sourceUrl: 'https://vercel.com/docs/cli',
        usageExample: 'ローカルで動作確認が終わったあと「Vercel に本番デプロイして」と指示するだけで、Claude Code が `vercel --prod` を実行しデプロイ URL を返してくれる。自分で CLI を操作する手順を覚える必要がない。',
      },
      {
        id: 'vercel-plugin',
        label: 'Vercel Plugin の導入',
        completed: true,
        description: 'Claude Code に Vercel 固有のスキルと知識を追加するプラグイン。',
        detail: 'Vercel Plugin を追加すると、vercel:deploy・vercel:env・vercel:ai-sdk などの専用スキルが利用可能になります。デプロイ戦略・環境変数管理・AI SDK 統合など Vercel 特有のベストプラクティスが自動的に適用されます。',
        commands: ['npx plugins add vercel/vercel-plugin --target claude-code -y'],
        sourceUrl: 'https://vercel.com/docs/integrations',
        usageExample: 'Next.js アプリの AI 機能を実装する際、「AI SDK を使ってストリーミングチャットを追加して」と伝えるだけで Vercel AI SDK の最新パターン（useChat・streamText）を使った実装が自動生成された。',
      },
      {
        id: 'settings-json',
        label: 'settings.json のカスタマイズ',
        completed: false,
        description: 'allowedTools や permissions を設定して Claude Code の動作を制御する。',
        detail: '`~/.claude/settings.json`（グローバル）または `.claude/settings.local.json`（プロジェクト）でツールの自動許可・Hooks・MCP サーバーを設定します。`permissions.allow` にパターンを列挙すると毎回の承認プロンプトをスキップできます。例: `"Bash(npm run:*)"` で npm スクリプト全般を自動許可。チームで共有する場合は `.claude/settings.json`（Git 管理）に置き、個人差分は `.claude/settings.local.json`（.gitignore）に分離します。',
        commands: [
          'cat ~/.claude/settings.json',
          'cat .claude/settings.local.json',
          '# permissions.allow の例:',
          '# "Bash(npm run:*)"  → npm スクリプト全般を自動許可',
          '# "Bash(git commit:*)"  → git commit を自動許可',
          '# "mcp__context7__query-docs"  → 特定 MCP ツールを自動許可',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/settings',
        usageExample: '毎回 `npm run lint` の実行に承認を求められて煩わしかったが、`"Bash(npm run:*)"` を `permissions.allow` に追加したところ、lint・build・test などの npm スクリプトがすべて自動実行されるようになりワークフローが大幅にスムーズになった。',
      },
    ],
  },
  {
    id: 'plan-checkpoints',
    label: 'Plan Mode & Checkpoints',
    icon: '📋',
    items: [
      {
        id: 'plan-mode',
        label: 'Plan Mode の使用',
        completed: true,
        description: '実装前に設計案をユーザーに提示し、承認を得てから実装を開始するフロー。',
        detail: 'Plan Mode では Claude Code が読み取り専用モードに切り替わり、コードベースを調査して実装計画をユーザーに提示します。複数のアプローチを比較・検討し、承認後にのみ実装を開始するため、手戻りを防げます。`EnterPlanMode` → 設計 → `ExitPlanMode` → 実装 の順で進みます。プランは `~/.claude/plans/` に Markdown ファイルとして保存されます。',
        commands: ['/plan'],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        usageExample: '認証機能をゼロから実装する前に Plan Mode で設計を確認したところ、「JWT の有効期限をリフレッシュトークンで更新する仕組みが抜けている」という見落としを実装前に発見できた。後から修正するコストが大幅に減った。',
      },
      {
        id: 'checkpoint-create',
        label: 'Checkpoint の作成・活用',
        completed: true,
        description: '実装の節目で状態を記録し、ロールバックの起点を作る。',
        detail: '`/checkpoint` コマンドで現在の git コミット SHA と日時を `.claude/checkpoints.log` に記録します。複雑な実装の途中で問題が発生した場合、記録した SHA まで `git reset` することで安全にロールバックできます。',
        commands: ['/checkpoint create "feature-start"', '/checkpoint list', '/checkpoint verify "feature-start"'],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        usageExample: 'UI リファクタリング前に `/checkpoint create "before-refactor"` を実行。リファクタリング中に意図せず別のコンポーネントが壊れたことに気づき、即座にロールバックして安全な状態から再挑戦できた。',
      },
      {
        id: 'checkpoint-rollback',
        label: 'Checkpoint からのロールバック',
        completed: true,
        description: '記録したチェックポイントの SHA まで git で戻す操作。',
        detail: '`/checkpoint verify` でチェックポイント以降の変更差分を確認できます。ロールバックする場合は `git reset --hard <SHA>` を使います。今回はピンクの画面を作成 → チェックポイントへ `git reset --hard c2c3084` でロールバックし、デフォルト画面に戻ることを確認しました。',
        commands: ['cat .claude/checkpoints.log', 'git reset --hard <sha>'],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        usageExample: '大規模なデータマイグレーションスクリプトをテストしたあと問題が発覚。チェックポイントに記録しておいた SHA へ即座にロールバックし、DB への影響を最小限に抑えることができた。',
      },
    ],
  },
  {
    id: 'hooks',
    label: 'Hooks',
    icon: '🪝',
    items: [
      {
        id: 'post-tool-use',
        label: 'PostToolUse Hook',
        completed: true,
        description: 'ファイル編集後に自動で lint・format を実行するフック。',
        detail: '`PostToolUse` フックは Write/Edit ツールが完了した直後に任意のシェルコマンドを実行します。実際の settings.json の構造は `hooks.PostToolUse` 配下に `{ matcher, hooks: [{ type, command, timeout?, async? }] }` の配列を並べる形式です。`matcher` に `"Write|Edit"` を指定するとファイル操作全般にマッチします。ツール入力は stdin に JSON で渡されます。',
        commands: [
          '# .claude/settings.local.json への追記例:',
          '# { "hooks": { "PostToolUse": [',
          '#   { "matcher": "Write|Edit",',
          '#     "hooks": [{ "type": "command",',
          '#       "command": "npm run lint 2>&1 | head -30" }] }',
          '# ] } }',
          'cat .claude/settings.local.json  # hooks セクション確認',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/hooks',
        usageExample: 'Claude Code がコンポーネントを編集するたびに自動で ESLint が走るよう設定。実際に unused import を含むコードを書いたところ、編集直後に lint エラーが表示され、Claude が即座に修正してくれた。手動で lint を実行する手間が完全になくなった。',
      },
      {
        id: 'pre-tool-use',
        label: 'PreToolUse Hook',
        completed: false,
        description: 'ツール実行前にバリデーションを行い、危険な操作をブロックするフック。',
        detail: '`PreToolUse` フックでツール実行前に任意のチェックを実行できます。スクリプトが exit code 2 を返すとツール実行がキャンセルされます（exit 0 は許可、exit 1 は警告のみ）。代表的な用途：①ファイルサイズ800行超のWrite をブロック、②secrets パターンを検出して Write を拒否、③`--no-verify` フラグ付きの Bash をブロック。ツール入力は stdin に JSON 形式で渡されます。',
        commands: [
          '# ファイルサイズガードの例 (exit 2 でブロック):',
          '# { "matcher": "Write",',
          '#   "hooks": [{ "type": "command",',
          '#     "command": "node -e \\"',
          '#       let d=\'\';process.stdin.on(\'data\',c=>d+=c);',
          '#       process.stdin.on(\'end\',()=>{',
          '#         const i=JSON.parse(d);',
          '#         const lines=(i.tool_input?.content||\'\').split(\'\\\\n\').length;',
          '#         if(lines>800){console.error(\'BLOCKED: \'+lines+\' lines\');process.exit(2)}',
          '#         console.log(d)})\\"',
          '#   }] }',
          '# --no-verify ブロック例:',
          '# { "matcher": "Bash", "hooks": [',
          '#   { "type": "command", "command": "npx block-no-verify@1.1.2" }',
          '# ] }',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/hooks',
        usageExample: '800行を超えるファイルを一度に生成しようとしたとき PreToolUse フックが自動ブロック。「ファイルを分割してください」というメッセージを受け取った Claude が自動的にモジュール分割した設計に切り替えた。コードの肥大化を構造的に防止できる。',
      },
      {
        id: 'stop-hook',
        label: 'Stop Hook',
        completed: false,
        description: 'セッション終了時に最終ビルド確認などを自動実行するフック。',
        detail: '`Stop` フックはセッションが終了する直前に実行されます。`npm run build` や `npm test` を設定しておくと、作業終了時に必ずビルドが通ることを確認できます。CI の代わりにローカルでの最終確認として活用できます。`async: true` を指定すると Claude の応答をブロックせずにバックグラウンドで実行できます。`timeout` を秒単位で指定しないとデフォルトの60秒でタイムアウトします。',
        commands: [
          '# Stop hook 設定例 (~/.claude/settings.json):',
          '# { "hooks": { "Stop": [',
          '#   { "matcher": "*",',
          '#     "hooks": [{ "type": "command",',
          '#       "command": "npm run build",',
          '#       "timeout": 120 }] }',
          '# ] } }',
          '# 非同期実行で Claude をブロックしない例:',
          '# { "type": "command", "command": "npm test", "async": true }',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/hooks',
        usageExample: '会話を終了するたびに自動でビルドが走るよう設定。ある日 TypeScript の型エラーをそのままにして会話を閉じようとしたとき Stop Hook が検知し、Claude がセッション終了前に型エラーを修正してくれた。壊れたコードを main にコミットする事故を防げた。',
      },
    ],
  },
  {
    id: 'subagents',
    label: 'Subagents & Agent ツール',
    icon: '🤖',
    items: [
      {
        id: 'explore-agent',
        label: 'Explore agent',
        completed: false,
        description: 'コードベースの調査・検索に特化した高速エージェント。',
        detail: 'Explore agent は Glob・Grep・Read ツールのみを持つ軽量エージェントで、ファイルパターン検索・キーワード検索・コードベースの把握を効率よく行います。Plan Mode の Phase 1 で複数の Explore agent を並列起動してコードベースを多角的に調査するのが典型的な使い方です。thoroughness レベルを "quick"・"medium"・"very thorough" で指定できます。',
        commands: [
          '# Agent ツール呼び出し例（会話内で Claude に指示）:',
          '# subagent_type: "Explore"',
          '# prompt: "src/components 配下の全コンポーネントを調べて',
          '#   props と依存関係をまとめてください"',
          '# → thoroughness: "medium" で中程度の調査',
          '# → thoroughness: "very thorough" で網羅的な調査',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/sub-agents',
        usageExample: '大規模リポジトリで「認証関連のコードをすべて調べて」と依頼したとき、Explore agent が src・tests・config の3箇所を並列で探索。メインの会話コンテキストを消費せずに詳細な調査結果が得られた。',
      },
      {
        id: 'planner-agent',
        label: 'Planner agent',
        completed: false,
        description: '実装計画の設計・アーキテクチャ検討に特化したエージェント。',
        detail: 'Planner agent は探索結果を受け取り、実装アプローチ・ファイル構成・依存関係・リスクを考慮した詳細な実装計画を返します。Plan Mode の Phase 2 で Explore の結果を渡してプランを生成させるパターンが効果的です。結果は `~/.claude/plans/` に Markdown ファイルとして保存され、実装フェーズで参照できます。',
        commands: [
          '# Agent ツール呼び出し例:',
          '# subagent_type: "Plan"',
          '# prompt: "以下の Explore 結果をもとに',
          '#   認証機能の実装計画を作成してください: ...',
          '#   ファイル構成・依存関係・リスクを含めること"',
          '# → プランファイルが ~/.claude/plans/ に保存される',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/sub-agents',
        usageExample: 'マイクロサービス分割の設計をゼロから考えるとき、Planner agent に「現在のモノリスコードを分析して、独立可能なドメインを特定し移行計画を作成して」と依頼。アーキテクチャ図・移行順序・リスク一覧が含まれた詳細な計画書が生成された。',
      },
      {
        id: 'code-reviewer-agent',
        label: 'Code Reviewer agent',
        completed: false,
        description: 'コード品質・セキュリティ・ベストプラクティスを自動レビューするエージェント。',
        detail: 'コードを書いた直後に Code Reviewer agent を起動することで、CRITICAL（セキュリティ脆弱性）・HIGH（バグ）・MEDIUM（品質）・LOW（スタイル）の4段階で問題を検出します。Security Reviewer agent と並列で使うとより網羅的なレビューになります。レビュー結果は直接会話に返ってきます。',
        commands: [
          '# Agent ツール呼び出し例:',
          '# subagent_type: "code-reviewer"',
          '# prompt: "src/app/api/auth/route.ts のコードを',
          '#   セキュリティと品質の観点でレビューしてください"',
          '# 並列起動例（1メッセージで2エージェント同時）:',
          '# Agent 1: subagent_type "code-reviewer"',
          '# Agent 2: subagent_type "security-reviewer"',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/sub-agents',
        usageExample: 'ユーザー入力を直接 SQL クエリに組み込むコードを書いたとき、Code Reviewer agent が CRITICAL レベルで SQL インジェクション脆弱性を検出。実装直後に問題を発見でき、本番リリース前に修正できた。',
      },
      {
        id: 'parallel-agents',
        label: '並列 agent 実行',
        completed: false,
        description: '独立した複数の調査・レビューを同時起動して効率化する。',
        detail: '1つのメッセージで複数の Agent ツール呼び出しを送ることで並列実行できます。Claude Code は複数の tool_use ブロックを同一ターンで返すことができ、それらは並列実行されます。コンテキストが独立した作業に効果的で、例えば「認証モジュールのセキュリティ調査」「キャッシュ層のパフォーマンス分析」「型定義の整合性チェック」を同時起動すると直列の3倍速で完了します。',
        commands: [
          '# 並列起動パターン（同一ターンで複数 Agent を宣言）:',
          '# Agent 1: subagent_type "Explore" → src/auth/**を調査',
          '# Agent 2: subagent_type "Explore" → src/api/**を調査',
          '# Agent 3: subagent_type "code-reviewer" → 最近の変更をレビュー',
          '# → 3つが同時実行され、すべての結果がまとめて返る',
          '# ※ 依存関係のある作業は並列にしない（順序が必要な場合は直列）',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/sub-agents',
        usageExample: 'PR レビュー前に「フロントエンドのパフォーマンス調査」「バックエンドのセキュリティ調査」「テストカバレッジ確認」を同時起動。3つの独立した分析が並行して走り、合計時間を約1/3に短縮できた。',
      },
      {
        id: 'background-agent',
        label: 'Background agent',
        completed: false,
        description: 'バックグラウンドで非同期実行し、完了時に通知を受け取るエージェント。',
        detail: '`run_in_background: true` を指定することで、エージェントの完了を待たずに他の作業を続けられます。時間のかかるテスト実行・ビルド確認などをバックグラウンドに回すことで、メインの会話フローをブロックせずに進められます。バックグラウンドエージェントが完了すると自動的に通知が届きます。SendMessage ツールで進行中のエージェントに追加指示を送ることも可能です。',
        commands: [
          '# Background agent 起動例:',
          '# Agent ツール: run_in_background: true',
          '# subagent_type: "general-purpose"',
          '# prompt: "全テストスイートを実行してカバレッジレポートを生成"',
          '# → 完了を待たずに次の会話を続けられる',
          '# → 完了時に自動通知が届く',
          '# → SendMessage ツールで途中経過を確認・追加指示が可能',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/sub-agents',
        usageExample: '2000件のテストスイートの実行を Background agent に依頼しつつ、別の機能実装を並行して進めた。テスト完了の通知が届いた時点でレポートを確認。待ち時間ゼロで両方の作業が完了した。',
      },
    ],
  },
  {
    id: 'mcp',
    label: 'MCP',
    icon: '🔌',
    items: [
      {
        id: 'mcp-setup',
        label: 'MCP サーバーの設定',
        completed: true,
        description: 'Model Context Protocol でClaude Codeに外部ツールを接続する。',
        detail: 'MCP（Model Context Protocol）は Claude Code に外部サービスや独自ツールを接続するための標準プロトコルです。`/mcp` コマンドで設定済みサーバーを確認・追加できます。設定は `~/.claude/settings.json` の `mcpServers` セクションに記述します。各サーバーは `command`・`args`・`env` で定義し、stdio または HTTP で通信します。',
        commands: [
          '/mcp',
          '# settings.json への mcpServers 追加例:',
          '# { "mcpServers": {',
          '#   "context7": {',
          '#     "command": "npx",',
          '#     "args": ["-y", "@upstash/context7-mcp@latest"]',
          '#   }',
          '# } }',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/mcp',
        usageExample: 'Slack MCP サーバーを設定することで、「昨日のデプロイに関する Slack スレッドを要約して」と Claude Code に依頼できるようになった。コードとドキュメントと会話ログを横断した分析が1つの会話で完結する。',
      },
      {
        id: 'context7',
        label: 'Context7 MCP',
        completed: true,
        description: 'ライブラリの最新ドキュメントをリアルタイムで取得するMCPサーバー。',
        detail: 'Context7 MCP を使うと、Next.js・Tailwind・Vercel SDK などのライブラリの最新 API ドキュメントをコンテキストに取り込めます。使い方は2ステップ：① `mcp__context7__resolve-library-id` でライブラリ名から ID を解決、② `mcp__context7__query-docs` で特定トピックのドキュメントを取得。学習データのカットオフ以降に更新された API も正確に参照できるため、古い API を使うミスを防げます。',
        commands: [
          '# Step 1: ライブラリ ID を解決',
          '# mcp__context7__resolve-library-id',
          '#   libraryName: "next.js"',
          '# → libraryId: "/vercel/next.js" が返る',
          '',
          '# Step 2: ドキュメントを取得',
          '# mcp__context7__query-docs',
          '#   context7CompatibleLibraryID: "/vercel/next.js"',
          '#   topic: "App Router data fetching"',
          '#   tokens: 5000',
        ],
        sourceUrl: 'https://context7.io',
        usageExample: 'Next.js の `fetch` キャッシュ挙動が v14→v15 で変わったことを知らずに古い書き方をしようとしたとき、Context7 が最新ドキュメントを取得して「v15 ではデフォルトがキャッシュなしになった」と教えてくれた。学習データのカットオフに起因するバグを未然に防止できた。',
      },
      {
        id: 'vercel-mcp',
        label: 'Vercel MCP サーバー',
        completed: true,
        description: 'Vercel のデプロイ・ログ・プロジェクト情報を Claude Code から操作する。',
        detail: 'Vercel MCP サーバーを接続すると、Claude Code の会話内からデプロイ・ログ・環境変数を直接操作できます。認証後は `/mcp` で "plugin:vercel:vercel" が "connected" になります。利用可能な主要ツール：list_teams・list_projects・list_deployments・get_deployment・get_runtime_logs・get_deployment_build_logs・deploy_to_vercel・check_domain_availability_and_price など20以上のツールが提供されます。',
        commands: [
          '/mcp  # 接続状態を確認',
          '# 利用可能な Vercel MCP ツール例:',
          '# mcp__plugin_vercel_vercel__list_deployments',
          '# mcp__plugin_vercel_vercel__get_deployment',
          '# mcp__plugin_vercel_vercel__get_runtime_logs',
          '# mcp__plugin_vercel_vercel__get_deployment_build_logs',
          '# mcp__plugin_vercel_vercel__deploy_to_vercel',
          '# mcp__plugin_vercel_vercel__list_projects',
        ],
        sourceUrl: 'https://vercel.com/docs/mcp',
        usageExample: '本番デプロイが失敗したとき、「最新デプロイのビルドログを確認して原因を教えて」と Claude Code に依頼。Vercel MCP が `get_deployment_build_logs` を呼び出してエラーログを取得・分析し、環境変数の設定ミスが原因だと特定してくれた。Vercel ダッシュボードを開かずに根本原因まで辿れた。',
      },
      {
        id: 'custom-mcp',
        label: 'カスタム MCP サーバーの作成',
        completed: false,
        description: '独自のツールやAPIをMCPサーバーとして実装してClaude Codeに接続する。',
        detail: '社内 API・データベース・独自ツールを MCP サーバーとして実装することで、Claude Code から直接操作できるようになります。Node.js（`@modelcontextprotocol/sdk`）や Python（`mcp`）で実装し、stdio または HTTP で通信します。設定は `~/.claude/settings.json` の `mcpServers` に追記します。環境変数は `env` フィールドで注入でき、`${ENV_VAR}` 形式で参照できます。',
        commands: [
          '# package.json に MCP SDK を追加:',
          '# npm install @modelcontextprotocol/sdk',
          '',
          '# settings.json への追記例:',
          '# { "mcpServers": {',
          '#   "my-api": {',
          '#     "command": "node",',
          '#     "args": ["./mcp-server/index.js"],',
          '#     "env": { "API_KEY": "${MY_API_KEY}" }',
          '#   }',
          '# } }',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/mcp',
        usageExample: '社内の Jira-like チケット管理システムを MCP サーバーとして実装。「今スプリントの未完了チケットを一覧して、優先度順に実装を進めて」と依頼するだけで、チケット取得→コード実装→ステータス更新まで Claude Code が自律的に処理するようになった。',
      },
    ],
  },
  {
    id: 'memory',
    label: 'Memory システム',
    icon: '🧠',
    items: [
      {
        id: 'memory-types',
        label: 'メモリの作成・管理',
        completed: false,
        description: 'user / feedback / project / reference の4種類のメモリで情報を永続化する。',
        detail: 'メモリは `~/.claude/projects/<project-hash>/memory/` に Markdown ファイルとして保存されます。各ファイルは YAML frontmatter（name・description・type）＋本文の形式。**user**: ユーザーの役割・好み、**feedback**: 作業スタイルの指示（Why と How to apply を明記）、**project**: 進行中の背景情報・締め切り、**reference**: 外部リソースへのポインタ、の4種類に分類します。MEMORY.md がインデックスとして機能し、毎セッション自動ロードされます。',
        commands: [
          '# メモリファイルの保存先:',
          '# ~/.claude/projects/<project-hash>/memory/',
          '',
          '# メモリファイルの形式例 (feedback_testing.md):',
          '# ---',
          '# name: no-mock-in-integration-tests',
          '# description: 統合テストでモックを使わない方針',
          '# type: feedback',
          '# ---',
          '# モックは使わず実際の DB に接続してテストする。',
          '# Why: モック/本番の乖離で本番移行時に失敗した経験がある。',
          '',
          '# MEMORY.md インデックスへの追記例:',
          '# - [no-mock-in-integration-tests](feedback_testing.md) — 統合テストは実DB使用',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/memory',
        usageExample: '「レスポンスの末尾にサマリーを書かないでください」と一度フィードバックしてメモリに保存。その後のすべてのセッションで同じ指摘をする必要がなくなり、Claude Code が常にその好みを反映してくれるようになった。',
      },
      {
        id: 'memory-index',
        label: 'MEMORY.md インデックスの整備',
        completed: false,
        description: 'メモリファイルへのポインタをまとめたインデックスを整理する。',
        detail: 'MEMORY.md は毎回の会話で自動的に読み込まれるインデックスファイルです。各エントリは1行・150文字以内に抑えます。200行を超えると切り捨てられるため、定期的に古くなったメモリを削除・統合して整理します。形式は `- [タイトル](ファイル名.md) — 1行の説明` です。',
        commands: [
          '# MEMORY.md の確認:',
          'cat ~/.claude/projects/$(ls ~/.claude/projects/ | head -1)/memory/MEMORY.md',
          '',
          '# メモリファイル一覧:',
          'ls ~/.claude/projects/$(ls ~/.claude/projects/ | head -1)/memory/',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/memory',
        usageExample: '数ヶ月プロジェクトを続けるうちにメモリが30件を超えた。MEMORY.md が200行に近づいたタイミングで古くなったプロジェクトメモリを削除・統合。インデックスをスリムに保つことでセッション冒頭のコンテキスト消費を最小化できた。',
      },
      {
        id: 'memory-usage',
        label: 'セッション間でのメモリ活用',
        completed: false,
        description: '過去の決定・好み・プロジェクト背景を次のセッションで自動参照する。',
        detail: '前回セッションで記録した feedback メモリ（「テストはモックを使わない」「サマリー不要」など）が次回セッションで自動的に適用されます。同じことを何度も説明する必要がなくなります。「これを記憶してください」と伝えると Claude がメモリファイルに保存します。「〇〇を忘れてください」と伝えると該当ファイルを削除します。メモリは会話内容ではなく非明白な情報（好み・背景・ルール）を保存するのに最適です。',
        commands: [
          '# メモリへの保存を依頼する例（会話で）:',
          '# 「テストでは必ずモックを避けて実 DB を使ってください。記憶してください。」',
          '# → Claude が memory/ に feedback ファイルを作成',
          '',
          '# メモリの削除を依頼する例（会話で）:',
          '# 「〇〇についての記憶を削除してください。」',
          '',
          '# メモリ内容を確認する例（会話で）:',
          '# 「記憶している内容を教えてください。」',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/memory',
        usageExample: '「このプロジェクトは pnpm を使っています。npm は使わないでください」と一度記憶させると、以降のセッションで npm コマンドを提案されることがなくなった。毎回説明するコストがゼロになり、会話がより本質的なタスクに集中できるようになった。',
      },
    ],
  },
  {
    id: 'skills',
    label: 'スキル (Skills)',
    icon: '🎯',
    items: [
      {
        id: 'builtin-skills',
        label: 'ビルトインスキルの活用',
        completed: false,
        description: '/commit・/review-pr などの組み込みスキルを使いこなす。',
        detail: 'Claude Code にはコミット・PR レビュー・コードレビューなど頻出タスクのスキルが組み込まれています。`/commit` を実行するとコードの変更を解析して適切なコミットメッセージを生成します。`/review-pr` では PR の差分を解析してレビューコメントを生成します。スキルは `/` プレフィックスで呼び出し、引数を渡すことも可能です。',
        commands: ['/commit', '/review-pr', '/checkpoint', '/plan', '/sessions'],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        usageExample: '機能実装が完了したあと `/commit` を実行すると、変更内容を解析して "feat: add JWT refresh token rotation with sliding window" のような意味のあるコミットメッセージを自動生成してくれた。毎回メッセージを考える時間がゼロになった。',
      },
      {
        id: 'vercel-skills',
        label: 'Vercel スキルの活用',
        completed: false,
        description: 'vercel:deploy・vercel:env などの専用スキルで Vercel 操作を効率化する。',
        detail: 'Vercel Plugin が提供するスキルには vercel:deploy（デプロイ戦略）・vercel:env（環境変数管理）・vercel:ai-sdk（AI SDK 統合）などがあります。スキルはプロンプト解析により自動的に適切なものが注入されます。`vercel env pull` で本番の環境変数をローカルに取得し、`vercel deploy --prod` で本番デプロイを実行できます。',
        commands: ['vercel env pull', 'vercel deploy --prod', 'vercel ls', 'vercel logs <deployment-url>'],
        sourceUrl: 'https://vercel.com/docs/cli',
        usageExample: '新しい環境変数を追加したとき、`vercel env pull` で最新の .env.local を取得してから実装を開始するようになった。ローカルと本番の環境差異によるバグがなくなった。',
      },
      {
        id: 'custom-skills',
        label: 'カスタムスキルの作成',
        completed: false,
        description: '繰り返し使う作業フローをスキルとして定義・再利用する。',
        detail: '`~/.claude/skills/` にマークダウンファイルを作成することでカスタムスキルを定義できます。スキルにはトリガー条件・実行手順・注意事項を記述し、`/skill-name` で呼び出せます。チームで共有する場合はリポジトリ内に置くこともできます。`/skill-create` スキルを使うと対話的にスキルファイルを生成できます。',
        commands: [
          '/skill-create',
          '# スキルファイルの保存先: ~/.claude/skills/<skill-name>.md',
          '# 呼び出し: /<skill-name>',
          'ls ~/.claude/skills/',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        usageExample: '毎週行うリリース作業（テスト実行→changelog 更新→バージョンバンプ→タグ付け→デプロイ）を `/release` スキルとして定義。以降は `/release 1.2.0` と打つだけで全ステップが自動実行されるようになった。',
      },
    ],
  },
  {
    id: 'advanced',
    label: '高度な機能',
    icon: '🚀',
    items: [
      {
        id: 'extended-thinking',
        label: 'Extended Thinking の制御',
        completed: false,
        description: 'Claude の内部推論トークンを制御して複雑な問題に対応する。',
        detail: 'Extended Thinking はデフォルトで有効で、最大 31,999 トークンの内部推論を行います。`Option+T`（macOS）/ `Alt+T`（Windows/Linux）でトグルでき、`MAX_THINKING_TOKENS` 環境変数で上限を設定できます。`Ctrl+O` で内部思考をリアルタイムで確認できます（Verbose モード）。アーキテクチャ設計・複雑なデバッグなど深い推論が必要なタスクで特に効果的です。コスト削減が必要な場合は `export MAX_THINKING_TOKENS=5000` で上限を下げます。',
        commands: [
          'export MAX_THINKING_TOKENS=10000  # 上限を 10000 token に設定',
          '# Option+T (macOS) → Extended Thinking をトグル',
          '# Ctrl+O → Verbose モードで内部思考を表示',
          '# ~/.claude/settings.json での永続設定:',
          '# { "alwaysThinkingEnabled": true }',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking',
        usageExample: '複雑な競合状態のバグを追っていたとき Extended Thinking を有効化。内部推論で「この async 処理と useEffect のクリーンアップが競合している」という仮説を10ステップかけて検証し、正確な修正方法を導き出してくれた。通常モードでは見落としていた原因だった。',
      },
      {
        id: 'multi-agent',
        label: 'Multi-agent ワークフロー',
        completed: false,
        description: '複数のエージェントを連携させて大規模タスクを分業処理する。',
        detail: '`/orchestrate` スキルを使うと、プランナー・実装者・レビュアーなど役割の異なる複数エージェントを協調させた複雑なワークフローを構築できます。典型的なフロー：① Explore agents でコードベース調査（並列）→ ② Plan agent で実装計画作成 → ③ 実装 agent が計画を実行 → ④ code-reviewer・security-reviewer でレビュー（並列）。1つのエージェントで完結しない大規模な機能開発・リファクタリングに適しています。',
        commands: [
          '/orchestrate',
          '# /multi-plan で複数プランを並列に設計',
          '# /multi-execute で並列実装を調整',
          '# /multi-workflow で全体フローを定義',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/sub-agents',
        usageExample: '5000行のモノリスを3つのモジュールに分割するリファクタリングを Multi-agent で実施。Explore×3・Plan×1・実装×3・Review×2 が連携して動き、1日かかる作業が2時間で完了した。',
      },
      {
        id: 'sessions',
        label: 'Sessions 管理',
        completed: false,
        description: '過去のセッションを再開・参照する機能。',
        detail: '`/sessions` コマンドで過去のセッション一覧を確認できます。各セッションにはサマリーと変更ファイル一覧が自動生成されます。長期プロジェクトで「先週の続きから」といった使い方が可能になります。`/resume-session` で特定のセッションを再開すると、そのセッションのコンテキストがロードされます。セッションサマリーは `~/.claude/plans/` や設定されたファイルに保存されます。',
        commands: [
          '/sessions  # 過去のセッション一覧を表示',
          '/resume-session  # 直前のセッションを再開',
          '/save-session  # 現在のセッションを手動保存',
          '# セッション間の継続には Memory システムも活用',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        usageExample: '数日間にわたる大型機能の実装中、毎朝 `/resume-session` で昨日のコンテキストを復元。前日「この部分は後で最適化する」と言っていた箇所を Claude が自動的に把握していて、「昨日保留にした DB クエリの最適化から始めましょうか？」と提案してくれた。',
      },
      {
        id: 'loop',
        label: '/loop による定期実行',
        completed: false,
        description: '指定間隔でコマンドやスキルを自動的に繰り返し実行する。',
        detail: '`/loop 5m /verify` のように指定するとデプロイ監視・テスト実行・ステータス確認などを一定間隔で自動実行できます。CI が走っている間の監視や、長時間バッチ処理の進捗確認に便利です。`/loop-status` で現在のループ状態を確認し、`/loop-start` で再起動できます。Stop hook と組み合わせるとループ終了時に自動クリーンアップも可能です。',
        commands: [
          '/loop 5m /verify  # 5分ごとに /verify を実行',
          '/loop 10m /build-fix  # 10分ごとにビルドエラーを自動修正',
          '/loop-status  # ループの実行状態を確認',
          '/loop-start  # 停止したループを再開',
        ],
        sourceUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        usageExample: 'データ移行バッチの実行中に `/loop 2m /verify` を起動。2分ごとに進捗と整合性チェックが自動実行され、途中でエラーが発生したタイミングを即座に検知できた。人が張り付いて監視する必要がなくなった。',
      },
    ],
  },
]
