import type { MasteryCategory } from '@/types/mastery'

export const MASTERY_CATEGORIES: MasteryCategory[] = [
  {
    id: 'setup',
    label: 'セットアップ・基盤',
    icon: '⚙️',
    items: [
      {
        id: 'claude-md',
        label: 'CLAUDE.md の作成',
        completed: true,
        description: 'プロジェクトのルールと規約をClaude Codeに伝えるための設定ファイル。',
        detail: 'CLAUDE.md はリポジトリのルートに置くことで、Claude Code がプロジェクトに参加するたびに自動的に読み込まれます。コーディング規約・ディレクトリ構成・コミットルール・禁止事項などを記述しておくと、会話のたびに説明する手間がなくなります。',
        commands: ['cat CLAUDE.md'],
      },
      {
        id: 'github-push',
        label: 'GitHub リポジトリの作成・プッシュ',
        completed: true,
        description: 'gh コマンドでリモートリポジトリを作成し、初回コミットをプッシュする。',
        detail: 'Claude Code は gh CLI を活用してリポジトリの作成・PR作成・Issue管理まで一貫して行えます。`gh repo create` でリポジトリを作成し、`git push -u origin main` で初回プッシュまで完結できます。',
        commands: ['gh repo create <name> --public', 'git push -u origin main'],
      },
      {
        id: 'vercel-deploy',
        label: 'Vercel デプロイ',
        completed: true,
        description: 'vercel CLI を使って login / link / deploy の一連のフローを実行する。',
        detail: 'Vercel へのデプロイは `vercel login` → `vercel link` → `vercel deploy` の3ステップ。プロジェクトを Vercel に紐付けると GitHub と連携し、プッシュのたびに自動デプロイが走るようになります。`--prod` フラグで本番環境に直接デプロイできます。',
        commands: ['vercel login', 'vercel link', 'vercel deploy', 'vercel --prod'],
      },
      {
        id: 'vercel-plugin',
        label: 'Vercel Plugin の導入',
        completed: true,
        description: 'Claude Code に Vercel 固有のスキルと知識を追加するプラグイン。',
        detail: 'Vercel Plugin を追加すると、vercel:deploy・vercel:env・vercel:ai-sdk などの専用スキルが利用可能になります。デプロイ戦略・環境変数管理・AI SDK 統合など Vercel 特有のベストプラクティスが自動的に適用されます。',
        commands: ['npx plugins add vercel/vercel-plugin --target claude-code -y'],
      },
      {
        id: 'settings-json',
        label: 'settings.json のカスタマイズ',
        completed: false,
        description: 'allowedTools や permissions を設定して Claude Code の動作を制御する。',
        detail: '`~/.claude/settings.json` でツールの自動許可・Hooks の設定・モデルの指定などが行えます。`allowedTools` に許可するツールを列挙すると、毎回の承認プロンプトをスキップできます。チームで共有する場合はリポジトリ内の `.claude/settings.json` に置きます。',
        commands: ['cat ~/.claude/settings.json'],
      },
    ],
  },
  {
    id: 'plan-checkpoints',
    label: 'Plan Mode & Checkpoints',
    icon: '📋',
    items: [
      {
        id: 'plan-mode',
        label: 'Plan Mode の使用',
        completed: true,
        description: '実装前に設計案をユーザーに提示し、承認を得てから実装を開始するフロー。',
        detail: 'Plan Mode では Claude Code が読み取り専用モードに切り替わり、コードベースを調査して実装計画をユーザーに提示します。複数のアプローチを比較・検討し、承認後にのみ実装を開始するため、手戻りを防げます。`EnterPlanMode` → 設計 → `ExitPlanMode` → 実装 の順で進みます。',
        commands: ['/plan'],
      },
      {
        id: 'checkpoint-create',
        label: 'Checkpoint の作成・活用',
        completed: true,
        description: '実装の節目で状態を記録し、ロールバックの起点を作る。',
        detail: '`/checkpoint` コマンドで現在の git コミット SHA と日時を `.claude/checkpoints.log` に記録します。複雑な実装の途中で問題が発生した場合、記録した SHA まで `git reset` することで安全にロールバックできます。',
        commands: ['/checkpoint create "feature-start"', '/checkpoint list', '/checkpoint verify "feature-start"'],
      },
      {
        id: 'checkpoint-rollback',
        label: 'Checkpoint からのロールバック',
        completed: true,
        description: '記録したチェックポイントの SHA まで git で戻す操作。',
        detail: '`/checkpoint verify` でチェックポイント以降の変更差分を確認できます。ロールバックする場合は `git reset --hard <SHA>` を使います。今回はピンクの画面を作成 → チェックポイントへ `git reset --hard c2c3084` でロールバックし、デフォルト画面に戻ることを確認しました。',
        commands: ['cat .claude/checkpoints.log', 'git reset --hard <sha>'],
      },
    ],
  },
  {
    id: 'hooks',
    label: 'Hooks',
    icon: '🪝',
    items: [
      {
        id: 'post-tool-use',
        label: 'PostToolUse Hook',
        completed: false,
        description: 'ファイル編集後に自動で lint・format を実行するフック。',
        detail: '`PostToolUse` フックは Write/Edit ツールが完了した直後に任意のシェルコマンドを実行します。`prettier --write` や `eslint --fix` を設定しておくと、Claude Code がファイルを編集するたびに自動フォーマットが走り、コードスタイルが常に統一されます。',
        commands: ['cat ~/.claude/settings.json  # hooks セクション確認'],
      },
      {
        id: 'pre-tool-use',
        label: 'PreToolUse Hook',
        completed: false,
        description: 'ツール実行前にバリデーションを行い、危険な操作をブロックするフック。',
        detail: '`PreToolUse` フックでファイルサイズ（800行超をブロック）・禁止パターン（secrets の書き込み等）を事前チェックできます。終了コード 2 を返すとツール実行がキャンセルされます。',
        commands: [],
      },
      {
        id: 'stop-hook',
        label: 'Stop Hook',
        completed: false,
        description: 'セッション終了時に最終ビルド確認などを自動実行するフック。',
        detail: '`Stop` フックはセッションが終了する直前に実行されます。`npm run build` や `npm run test` を設定しておくと、作業終了時に必ずビルドが通ることを確認できます。CI の代わりにローカルでの最終確認として活用できます。',
        commands: [],
      },
    ],
  },
  {
    id: 'subagents',
    label: 'Subagents & Agent ツール',
    icon: '🤖',
    items: [
      {
        id: 'explore-agent',
        label: 'Explore agent',
        completed: false,
        description: 'コードベースの調査・検索に特化した高速エージェント。',
        detail: 'Explore agent は Glob・Grep・Read ツールに特化しており、ファイルパターン検索・キーワード検索・コードベースの把握を効率よく行います。Plan Mode の Phase 1 で複数の Explore agent を並列起動してコードベースを多角的に調査するのが典型的な使い方です。',
        commands: [],
      },
      {
        id: 'planner-agent',
        label: 'Planner agent',
        completed: false,
        description: '実装計画の設計・アーキテクチャ検討に特化したエージェント。',
        detail: 'Planner agent は探索結果を受け取り、実装アプローチ・ファイル構成・依存関係・リスクを考慮した詳細な実装計画を返します。Plan Mode の Phase 2 で Explore の結果を渡してプランを生成させるパターンが効果的です。',
        commands: [],
      },
      {
        id: 'code-reviewer-agent',
        label: 'Code Reviewer agent',
        completed: false,
        description: 'コード品質・セキュリティ・ベストプラクティスを自動レビューするエージェント。',
        detail: 'コードを書いた直後に Code Reviewer agent を起動することで、CRITICAL（セキュリティ脆弱性）・HIGH（バグ）・MEDIUM（品質）・LOW（スタイル）の4段階で問題を検出します。Security Reviewer agent と並列で使うとより網羅的なレビューになります。',
        commands: [],
      },
      {
        id: 'parallel-agents',
        label: '並列 agent 実行',
        completed: false,
        description: '独立した複数の調査・レビューを同時起動して効率化する。',
        detail: '1つのメッセージで複数の Agent ツール呼び出しを送ることで並列実行できます。例：「認証モジュールのセキュリティ調査」「キャッシュ層のパフォーマンス分析」「型定義の整合性チェック」を同時に走らせるといったパターン。コンテキストが独立している作業に効果的です。',
        commands: [],
      },
      {
        id: 'background-agent',
        label: 'Background agent',
        completed: false,
        description: 'バックグラウンドで非同期実行し、完了時に通知を受け取るエージェント。',
        detail: '`run_in_background: true` を指定することで、エージェントの完了を待たずに他の作業を続けられます。時間のかかるテスト実行・ビルド確認などをバックグラウンドに回すことで、メインの会話フローをブロックせずに進められます。',
        commands: [],
      },
    ],
  },
  {
    id: 'mcp',
    label: 'MCP',
    icon: '🔌',
    items: [
      {
        id: 'mcp-setup',
        label: 'MCP サーバーの設定',
        completed: false,
        description: 'Model Context Protocol でClaude Codeに外部ツールを接続する。',
        detail: 'MCP（Model Context Protocol）は Claude Code に外部サービスや独自ツールを接続するための標準プロトコルです。`/mcp` コマンドで設定済みサーバーを確認・追加できます。設定は `~/.claude/settings.json` の `mcpServers` セクションに記述します。',
        commands: ['/mcp'],
      },
      {
        id: 'context7',
        label: 'Context7 MCP',
        completed: false,
        description: 'ライブラリの最新ドキュメントをリアルタイムで取得するMCPサーバー。',
        detail: 'Context7 MCP を使うと、Next.js・Tailwind・Vercel SDK などのライブラリの最新 API ドキュメントをコンテキストに取り込めます。学習データのカットオフ以降に更新された API も正確に参照できるため、古い API を使うミスを防げます。',
        commands: [],
      },
      {
        id: 'vercel-mcp',
        label: 'Vercel MCP サーバー',
        completed: false,
        description: 'Vercel のデプロイ・ログ・プロジェクト情報を Claude Code から操作する。',
        detail: 'Vercel MCP サーバーを接続すると、デプロイ一覧の取得・ログの確認・環境変数の管理などを Claude Code の会話内から直接行えます。デプロイ失敗の原因調査や本番環境の状態確認がよりスムーズになります。',
        commands: [],
      },
      {
        id: 'custom-mcp',
        label: 'カスタム MCP サーバーの作成',
        completed: false,
        description: '独自のツールやAPIをMCPサーバーとして実装してClaude Codeに接続する。',
        detail: '社内 API・データベース・独自ツールを MCP サーバーとして実装することで、Claude Code から直接操作できるようになります。Node.js・Python などで MCP SDK を使って実装し、stdio または HTTP で通信します。',
        commands: [],
      },
    ],
  },
  {
    id: 'memory',
    label: 'Memory システム',
    icon: '🧠',
    items: [
      {
        id: 'memory-types',
        label: 'メモリの作成・管理',
        completed: false,
        description: 'user / feedback / project / reference の4種類のメモリで情報を永続化する。',
        detail: 'メモリは `~/.claude/projects/<project>/memory/` に Markdown ファイルとして保存されます。user: ユーザーの役割・好み、feedback: 作業スタイルの指示、project: 進行中の背景情報、reference: 外部リソースへのポインタ、の4種類に分類します。MEMORY.md がインデックスとして機能します。',
        commands: [],
      },
      {
        id: 'memory-index',
        label: 'MEMORY.md インデックスの整備',
        completed: false,
        description: 'メモリファイルへのポインタをまとめたインデックスを整理する。',
        detail: 'MEMORY.md は毎回の会話で自動的に読み込まれるインデックスファイルです。各エントリは1行・150文字以内に抑えます。200行を超えると切り捨てられるため、定期的に古くなったメモリを削除・統合して整理します。',
        commands: ['cat ~/.claude/projects/<project>/memory/MEMORY.md'],
      },
      {
        id: 'memory-usage',
        label: 'セッション間でのメモリ活用',
        completed: false,
        description: '過去の決定・好み・プロジェクト背景を次のセッションで自動参照する。',
        detail: '前回セッションで記録した feedback メモリ（「テストはモックを使わない」「サマリー不要」など）が次回セッションで自動的に適用されます。同じことを何度も説明する必要がなくなり、会話がより効率的になります。',
        commands: [],
      },
    ],
  },
  {
    id: 'skills',
    label: 'スキル (Skills)',
    icon: '🎯',
    items: [
      {
        id: 'builtin-skills',
        label: 'ビルトインスキルの活用',
        completed: false,
        description: '/commit・/review-pr などの組み込みスキルを使いこなす。',
        detail: 'Claude Code にはコミット・PR レビュー・コードレビューなど頻出タスクのスキルが組み込まれています。`/commit` を実行するとコードの変更を解析して適切なコミットメッセージを生成します。`/review-pr` では PR の差分を解析してレビューコメントを生成します。',
        commands: ['/commit', '/review-pr', '/checkpoint'],
      },
      {
        id: 'vercel-skills',
        label: 'Vercel スキルの活用',
        completed: false,
        description: 'vercel:deploy・vercel:env などの専用スキルで Vercel 操作を効率化する。',
        detail: 'Vercel Plugin が提供するスキルには vercel:deploy（デプロイ戦略）・vercel:env（環境変数管理）・vercel:ai-sdk（AI SDK 統合）などがあります。スキルはプロンプト解析により自動的に適切なものが注入されます。',
        commands: ['vercel env pull', 'vercel deploy --prod'],
      },
      {
        id: 'custom-skills',
        label: 'カスタムスキルの作成',
        completed: false,
        description: '繰り返し使う作業フローをスキルとして定義・再利用する。',
        detail: '`~/.claude/skills/` にマークダウンファイルを作成することでカスタムスキルを定義できます。スキルにはトリガー条件・実行手順・注意事項を記述し、`/skill-name` で呼び出せます。チームで共有する場合はリポジトリ内に置くこともできます。',
        commands: ['/skill-create'],
      },
    ],
  },
  {
    id: 'advanced',
    label: '高度な機能',
    icon: '🚀',
    items: [
      {
        id: 'extended-thinking',
        label: 'Extended Thinking の制御',
        completed: false,
        description: 'Claude の内部推論トークンを制御して複雑な問題に対応する。',
        detail: 'Extended Thinking はデフォルトで有効で、最大 31,999 トークンの内部推論を行います。`Option+T`（macOS）でトグルでき、`MAX_THINKING_TOKENS` 環境変数で上限を設定できます。アーキテクチャ設計など深い推論が必要なタスクで特に効果的です。',
        commands: ['export MAX_THINKING_TOKENS=10000'],
      },
      {
        id: 'multi-agent',
        label: 'Multi-agent ワークフロー',
        completed: false,
        description: '複数のエージェントを連携させて大規模タスクを分業処理する。',
        detail: 'orchestrate スキルを使うと、プランナー・実装者・レビュアーなど役割の異なる複数エージェントを協調させた複雑なワークフローを構築できます。1つのエージェントで完結しない大規模な機能開発やリファクタリングに適しています。',
        commands: ['/orchestrate'],
      },
      {
        id: 'sessions',
        label: 'Sessions 管理',
        completed: false,
        description: '過去のセッションを再開・参照する機能。',
        detail: '`/sessions` コマンドで過去のセッション一覧を確認し、特定のセッションを再開できます。長期プロジェクトで「先週の続きから」といった使い方が可能になります。セッションサマリーも自動生成されます。',
        commands: ['/sessions', '/resume-session'],
      },
      {
        id: 'loop',
        label: '/loop による定期実行',
        completed: false,
        description: '指定間隔でコマンドやスキルを自動的に繰り返し実行する。',
        detail: '`/loop 5m /verify` のように指定するとデプロイ監視・テスト実行・ステータス確認などを一定間隔で自動実行できます。CI が走っている間の監視や、長時間バッチ処理の進捗確認に便利です。',
        commands: ['/loop 5m /verify', '/loop-status', '/loop-start'],
      },
    ],
  },
]
